apiVersion: v1
kind: Namespace
metadata:
  name: asset-sbox-eck
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: eck-sbox001-filebeat
  namespace: asset-sbox-eck
spec:
  type: filebeat
  version: 9.2.3
  elasticsearchRef:
    name: eck-sbox001-es
    namespace: asset-sbox-eck
  kibanaRef:
    name: eck-sbox001-kb
    namespace: asset-sbox-eck
  config:
    filebeat.autodiscover.providers: 
    - node: ${NODE_NAME}
      type: kubernetes
      hints.enabled: true
      hints.default_config.enabled: false
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: eck-sbox001-filebeat-sa
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eck-sbox001-filebeat-cr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eck-sbox001-filebeat-sa
  namespace: asset-sbox-eck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eck-sbox001-filebeat-crb
subjects:
- kind: ServiceAccount
  name: eck-sbox001-filebeat-sa
  namespace: asset-sbox-eck
roleRef:
  kind: ClusterRole
  name: eck-sbox001-filebeat-cr
  apiGroup: rbac.authorization.k8s.io
