apiVersion: v1
kind: Namespace
metadata:
  name: asset-sbox-kafka
  labels:
    project: assets
    group: kafka
---
# Kafka NodePool (optional for Strimzi 2.x)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-sbox001-pool
  namespace: asset-sbox-kafka
  labels:
    strimzi.io/cluster: kafka-sbox001-cluster
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
---
# Kafka Cluster
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-sbox001-cluster
  namespace: asset-sbox-kafka
  annotations:
    strimzi.io/kafka-cert-secret-issuer: cluster-issuer
spec:
  kafka:
    replicas: 1
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}


