apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: security-crowdsec-release
  namespace: infra-release-helm
spec:
  repo: https://crowdsecurity.github.io/helm-charts
  chart: crowdsec
  targetNamespace: infra-crowdsec-security
  createNamespace: true
  valuesContent:  |-
    container_runtime: containerd
    agent:
      acquisition:
        - namespace: kube-system
          podName: traefik-*
          program: traefik
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/traefik"
    lapi:
      env:
        - name: ENROLL_KEY
          value: "cmjxcik60000e02jsypbkii1h"
        - name: ENROLL_INSTANCE_NAME
          value: "k3sv2"
        - name: ENROLL_TAGS
          value: "k8s linux test"
---
#cscli bouncers add traefik-bouncer
#traefik.ingress.kubernetes.io/router.middlewares: infra-crowdsec-security-crowdsec-bouncer@kubernetescrd
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: crowdsec-bouncer
    namespace: infra-crowdsec-security
spec:
    plugin:
        crowdsec-bouncer-traefik-plugin:
            CrowdsecLapiKey: "DLxB1Rc8hPfS7k7mjecqEOFGmZiwILP3569QSR5HLdQ"
            crowdsecLapiHost: "security-crowdsec-release-service.infra-crowdsec-security.svc.cluster.local"
            crowdsecLapiPort: "8080"
            crowdsecAppsecScheme: http
            Enabled: true
            logLevel: DEBUG
            crowdsecMode: appsec