apiVersion: v1
kind: Secret
metadata:
  name: dev-pythondev.v2.miom.am-codeserver-secret
  namespace: host-pythondev-dev
type: Opaque
stringData:
  PASSWORD: R8CczRurDtsbr5Q8DNdpecDH
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-pythondev.v2.miom.am-codeserver-bootstrap
  namespace: host-pythondev-dev
data:
  bootstrap.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    echo "[bootstrap] apt update/upgrade + install deps"
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    sudo apt-get install --reinstall -y ca-certificates
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
      iputils-ping \
      python3.11 python3.11-venv python3.11-dev python3-pip \
      mariadb-client \
      libmariadb-dev \
      build-essential \
      pkg-config \
      nodejs npm
    sudo apt-get clean
    sudo rm -rf /var/lib/apt/lists/*

    echo "[bootstrap] code-server extensions"
    code-server --install-extension ms-python.python
    code-server --install-extension ms-toolsai.jupyter

    echo "[bootstrap] python/pip setup"
    python3 -m pip config set global.break-system-packages true
    pip install ipykernel -U --user --force-reinstall

    # install python deps (mysql + mariadb)
    pip install --user -U \
      mysql-connector-python \
      mariadb \
      paramiko requests pika pandas kubernetes

    echo "[bootstrap] git config"
    git config --global user.name "Vahan"
    git config --global user.email "yeranosyanvahan@gmail.com"

    echo "[bootstrap] ensure project dir"
    mkdir -p /home/coder/project

    echo "[bootstrap] update node"
    sudo apt remove -y nodejs 
    sudo apt purge -y nodejs 
    sudo apt autoremove -y 
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt install -y nodejs && node -v && npm -v


    echo "[add emmet] done"    
    mkdir -p ~/.config/Code/User && echo '{ "emmet.triggerExpansionOnTab": true }' > ~/.config/Code/User/settings.json

    echo "[bootstrap] done"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pythondev.v2.miom.am-codeserver-pvc
  namespace: host-pythondev-dev
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dev-pythondev-comonal-miom-am-codeserver-svc
  namespace: host-pythondev-dev
spec:
  type: ClusterIP
  selector:
    app: code-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-pythondev.v2.miom.am-codeserver-ingress
  namespace: host-pythondev-dev
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pythondev.v2.miom.am
      secretName: pythondev.v2.miom.am-tls
  rules:
    - host: pythondev.v2.miom.am
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-pythondev-comonal-miom-am-codeserver-svc
                port:
                  number: 80
